<h4><u>Terms of Service</u></h4><br><br>

Adgo.tv’s Terms of Service (“TOS”) is an electronic contract between Adgo.tv and Publishers, in which Adgo.tv agrees to allow Publishers to provide their users with the ability to view Licensor Content on Publisher’s websites, applications, and/or other digital channels via embedded Adgo.tv players and/or other delivery platforms, and Publishers agree that all Content will be hosted on Adgo.tv’s sites and servers and streamed through the above channels.  The terms “Licensor Content” and “Content” are defined in the TOS as any data, video, audio, metadata, metatags, tagging and/or other breakdown, definition/partition of video, film/TV clips and segments, applications, processes, search and results, look and feel, clips, text, title, description, feeds and/or any other content  made available by Adgo.tv.  The terms “we” and “us” are used in reference to Adgo.tv.  The terms “you” and “your” refer to Publishers.  By accepting Adgo.tv's Terms of Service (“The TOS”), you agree to adhere to the following policies<br><br>
The TOS constitutes the entire understanding of Adgo.tv and Publishers, and is intended as a final expression of our agreement.  Adgo.tv may modify, change, or amend the TOS at our sole discretion, at any time.  Any and all modifications, changes, and/or amendments to the TOS will be posted here.  You are responsible for keeping up-to-date with and adhering to all the terms and conditions in the TOS, which takes precedence over any other document.  If you fail to comply with the TOS without the express, written consent of Adgo.tv, we may disable ad serving to your site and/or your Adgo.tv account at any time. <b>If your account is disabled, you will no longer be eligible for further participation in the Adgo.tv program and you will not receive any payment.</b><br><br> 
<h4>Invalid Clicks & Impressions</h4><br><br>
Clicking your own ads for any reason is prohibited and is considered fraudulent activity.  Clicks on Adgo.tv ads must result from genuine user interest.  Any method that artificially generates clicks or impressions on your Adgo.tv ads is strictly prohibited. These prohibited methods include, but are not limited to: repeated manual clicks or impressions; automated click and impression generating tools; the use of robot, automated programs, or deceptive software; and/or clicks without referring URL’s. <br><br>
<h4>Encouraging clicks</h4><br><br>
Asking or encouraging users to click Adgo.tv ads is prohibited as is the use of deceptive implementation methods to obtain clicks.  This includes, but is not limited to: offering compensation to users for viewing ads and/or performing searches; promising compensation to third parties for such behavior; placing misleading images next to individual ads; using phrases such as “click the ads,” “support us,” “visit these links,” or other similar language; directing user attention to ads using arrows or other graphical gimmicks; placing ads in floating box scripts; and/or formatting site contents so that ads are indistinguishable or difficult to distinguish from site content.<br><br>

<h4>Copyrighted material</h4><br><br>

You are not granted access to or rights in any Content, sites, or data that belong to Adgo.tv or its licensors and are therefore prohibited from asserting in any manner to any party in any forum that you own any interests in copyrights or other rights to Licensor Content.   You are not to display Adgo.tv ads on webpages with copyrighted content unless they have the necessary legal rights to display that content. Publishers are responsible for obtaining all performance rights licenses. <br><br> 

<h4>Traffic sources</h4><br><br>

Adgo.tv ads may not be placed on pages receiving traffic from certain sources. For example, Publishers may not participate in paid-to-click programs, send unwanted emails, or display ads as the result of the action of any software application.   In order to ensure a positive experience for users and Adgo.tv advertisers, sites displaying Adgo.tv ads must not: use services that generate clicks or impressions, such as paid-to-click, paid-to-surf, autosurf, and click-exchange programs; encourage or allow users to purchase traffic in any way, shape, or form; be promoted through unsolicited mass emails or unwanted advertisements on third-party website; and/or be engaged with or use any software which can trigger pop-ups, redirect users to unwanted websites, modify browser settings, or otherwise interfere with site navigation.  Publishers are responsible for ensuring no ad network or affiliate uses such methods to direct traffic to pages that contain your Adgo.tv code.
Content guidelines
Publishers are strictly forbidden from placing Adgo.tv code on pages/sites that include or link to: 
•	Pornography, adult, or mature content
•	Violent content
•	Content related to racial intolerance or advocacy against any individual, group or organization
•	Excessive profanity
•	Firearms
•	Hacking/cracking content
•	Gambling or casino-related content
•	Illicit drugs and drug paraphernalia content
•	Intimate personal hygiene
•	Politics
•	Prostitution
•	Sales of beer or hard alcohol
•	Sales of tobacco or tobacco-related products
•	Sales of prescription drugs
•	Violence
•	Content regarding programs which compensate users for clicking ads or offers, performing searches, surfing websites, or reading emails
•	Any other content that is illegal, promotes illegal activity, or infringes on the legal rights of others
Publishers are not to purchase any traffic from any URL which allows placement of any advertisement or content in connection with the Content in any manner that: 
•	induces, promotes, or facilitates copyright infringement; 
•	sells goods or services that enable the circumvention of copy protection technologies; 
•	promotes web sites, companies, or services identified in writing by Adgo.tv as involved with any of the above; 
•	offers or disseminates fraudulent goods, services, schemes, or promotions, including any make-money-fast or pyramid schemes; 
•	promotes illegal activity such as copyright infringement, racism, hate, mail fraud, spam, pyramid schemes, or other advice not permitted under applicable law; 
•	promotes or contains libelous and defamatory material, violates privacy rights, and/or is contrary to public policy or otherwise unlawful.

<h4>Take Down Orders</h4><br><br>
Adgo.tv reserves the right to require Publisher to cease presentation of any advertisement or content in connection with Licensor Content if it is believed to have a material adverse effect on the Content, Adgo.tv, Content right owners, or Adgo.tv’s rights to the Content or its services.  Once a Take Down Order has been given, you are required to remove advertisements or content within twenty-four (24) hours of receiving written notice.  Such a “Take Down Order” will not, unless otherwise provided, affect other Licensed Content.  
Ad behavior
Publishers are only authorized to use Licensor Content in the as-is distribution of the feed or stream provided by Adgo.tv.  You are prohibited from modifying, altering, copying, downloading, or creating derivative works of any Licensor Content and are not to use Licensor Content in any advertisement or any other manner, except for the as-is distribution of the feed or stream  provided by Adgo.tv.  You are prohibited from using Licensor Content in the form of product endorsements or commercial tie-ups and are further prohibited from allowing advertisements, endorsements, or tying-up of the Content or any portion thereof.  

Publishers are not to alter, copy, or remove the phrase “Powered by Adgo.tv,” which is a link to Adgo.tv’s website at the URL http://wiki.Adgo.tv.com/Adgo.tv-api/api-license-agreement in conjunction with the use of Licensor Content, whether on an Adgo.tv customized player or by way of an API license.
Ad placement
Publishers are encouraged to experiment with a variety of placements and ad formats. However, Adgo.tv code may not be placed in inappropriate places such as pop-ups, emails, or software. You must also adhere to the policies for each product used. 

Adgo.tv ads, search boxes or search results may not (be): 
•	Exceed more than 3 ad units per page.
•	Displayed on any site and/or page that is not previously approved by the  Policy Team
•	Displayed in pop-ups or pop-unders (without the approval of Adgo.tv)
•	Obscured by elements on a page.
•	Placed on any non-content-based page.
•	Placed on pages published specifically for the purpose of showing ads.
•	Placed on pages whose content or URL could confuse users into thinking it is associated with Adgo.tv due to the misuse of logos, trademarks or other brand features.
•	Placed on, within, or alongside other third products or services in a manner that violates the policies of that product or service.
Site behavior
Publishers are to use commercially reasonable efforts to promote access to the Content, attract advertisers to it, and collect from said advertisers.  Sites showing Adgo.tv ads should be easy for users to navigate. Sites may not change user preferences, redirect users to unwanted websites, initiate downloads, include malware, or contain pop-ups or pop-unders that interfere with site navigation.

You are not to modify or adversely influence any content security applied by Adgo.tv and its licensors, and agree to comply with the content security obligations set forth herein and as provided or applied by Adgo.tv.  Publishers agree not to block or otherwise alter the promotional “Call to Action” as contained in either the embeddable Adgo.tv player or video, post-rolls, skins, pre-rolls, CTAs or any other attached advertising, trademarks, copyright management information, licenses, instruments, or information published by Adgo.tv in connection with Licensor Content.  You are prohibited from inserting any advertisement of any kind on the Adgo.tv proprietary player.  
Advertising Cookies/Online Behavioral Advertising.  
Publishers are to include in its privacy policy on its websites: (i) notice that online behavioral advertising (“OBA”) and/or multi-site advertising is occurring (which should explain in plain English that information about the user’s internet use, gathered through cookies, web beacons, and similar means, is being used to select the advertisements displayed on the URL so that they are more likely to be of interest to the user); (ii) a description of the types of data that are collected for OBA and/or multi-site advertising purposes (e.g., click stream information, browser type, time and date, subject of advertisements clicked or scrolled over); (iii) an explanation of how and for what purpose any data collected for OBA and/or multi-site advertising purposes will be used or transferred to third parties; and (iv) a conspicuous link to the OBA opt-out page on the Network Advertising Initiative website (presently located at http://www.networkadvertising.org/managing/opt_out.asp).  

Minimum Traffic Requirements
Adgo.tv reserves the right to terminate this agreement should, according to Adgo.tv’s statistics, the number of Impressions delivered by the Publisher total less than 750,000 impressions per month (or 25,000 impressions per day) for all website(s) in the Publishers' account.
Reporting Requirements 
The term “Advertising Revenue” is defined in Adgo.tv’s TOS as all amounts earned and actually collected by Adgo.tv resulting from the sale of third party player advertising, less: (a) any actual and directly related commissions or fees paid in connection with such revenue, and (b) finance, VAT, excise or similar taxes legally collected on the revenue as evidenced by invoice.
Both Adgo.tv and Publisher are to keep and maintain complete and accurate records (the “Records”) in sufficient detail to enable any amount payable under the TOS to be determined.  Any party collecting Advertising Revenue in association with the Content will provide the other party with a detailed written report in a form acceptable by both parties (the “Reports”) describing the Content displayed and any advertisement published in connection therewith, including but not limited to: number of ad impressions in period, average CPM in period, and revenue.  Parties agree to use their best efforts to provide Reports no less frequently than every month within 30 days after month’s end.  Upon written request of either party, the other party will provide access to such Records during normal business hours as may be reasonably necessary to verify the accuracy of the Reports.
Payments
Any amount due to the receiving party is to be paid within 90 days from the end of the month in which such revenues have been reported and collected.  All amounts payable will be paid in US dollars, exclusive of any applicable value added, use, sale, or similar taxes.
Taxes and Withholdings
Adgo.tv and Publisher agree to collaborate and use their best commercial efforts to reduce any tax or withholding of governmental or taxing local authorities on payments hereunder or secure exemptions therefrom, to the extent available.  To the extent an exemption is not obtained, each party will be allowed to deduct any applicable tax or withholdings of governmental or taxing local authorities required for the transfer of amounts payable to the other party from the gross amounts payable to the other party.  Each party will supply to the other party all necessary, related, required, identifying information and withholding certificates on a timely basis.
Confidential Information
Adgo.tv and Publisher agree that neither party will disclose to any third party any Confidential Information without the express, written consent of the other party.  “Confidential Information” is defined herein as any information, oral or written, treated as confidential that relates to any party’s past, present, or future proprietary information or data, including without limitation, research, development, business activities, and/or any unannounced products.  Confidential Information will not be deemed to include information that: (i) is publicly available or in the public domain at the time disclosed; (ii) is or becomes publicly available or enters the public domain through no fault of the party receiving such information; (iii) is rightfully communicated to the recipient by persons not bound by confidentiality obligations with respects thereto; or (iv) is already in the recipient’s possession free of any confidentiality obligations with respect thereto at the time of disclosure.
Proprietary Information
Publisher is not granted any rights, licenses, titles, or interest to any hardware, software, programs, codes, trade names, technology, intellectual property, licenses, patents, trademarks, copyrights, trade secrets, know-how, or processes owned, used, or licensed by Adgo.tv, including Adgo.tv’s proprietary player, software, databases, and other aspects and technologies related to Adgo.tv’s technology, including any enhancements, modifications, improvements, or derivatives), or any Content.  You are not granted any other proprietary rights, use, intellectual property, or confidential information, whether express or implied, except as expressly provided herein, all of which is to remain with Adgo.tv.
Notices
Any notice required to be given pursuant to the TOS will be in writing and mailed by certified mail, return receipt requested, or delivered by a nation overnight express service, effective upon receipt or by email of the email provided a return receipt, effective upon the return of the email return receipt.  Either party may change the address to which the notice or payment is to be sent by written notice to the other party pursuant to the provisions of this paragraph.
Representations and Warranties
Adgo.tv makes no implied or specific representations or warranties as to: (i) the availability of any specific title or part of the Content; (ii) the continuous access to or inclusion of any current or future Content; (iii) the accuracy, completeness, or sufficiency of any part of the Content or its compatibility for any purpose; (iv) the continuous or uninterrupted services or access to Content or Adgo.tv site or players; or (v) the integration or manner of presenting the Content on Publisher’s applications, channels, or otherwise.

Adgo.tv will provide its products, applications, players, API, site, services, and/or Content “AS IS, WHERE IS.”  These products, applications, players, API, site, services, and/or Content are subject to all restrictions applicable.

Adgo.tv makes no warranties relating to its intellectual property, products, services, site, player, and/or Content, express or implied, and expressly disclaims any warranty of non-infringement, fitness for a particular purpose or merchantability.  No person is authorized to make any warranty or representation concerning the performance of Adgo.tv’s intellectual property, products, players, site, services, and/or Content other than as provided in this section.  In no event shall Adgo.tv be liable to Publisher, any end user, or third party for incidental, indirect, special, or consequential damages, or for lost profits, work stoppage, savings, or revenues of any kind, or for lost data, damage to other software, computer failure or malfunction or downtime, regardless of whether Adgo.tv has advised or has been advised of the possibility of such damages.  Without limiting the foregoing, Adgo.tv does not warrant that the functions or materials contained within the Content, site or players will meet Publisher’s and/or Publisher’s Website users’ or advertisers’ requirements, or will operate in any combination which may be selected for use, or that operation of its intellectual property and/or Content will be uninterrupted or error-free, or that any defects that may exist in the products, services, and/or Content will be corrected.

Indemnification

The Publisher agrees to indemnify and hold  harmless Adgo.tv and its affiliates, employees, agents and representatives from and against any and all claims, demands, liabilities, expenses, losses, damages, and/or attorney fees arising in connection with any and all claims, lawsuits, and actual losses for libel, slander, copyright, and trademark violation as well as all other claims resulting from (i) the participation of the Publisher in the  Network, (ii) operation of the Publisher’s Site(s) submitted to  for participation in the  Network or (iii) otherwise arising from Publisher’s relationship with Adgo.tv. The Publisher also agrees to indemnify Adgo.tv for any legal fees incurred by Adgo.tv, acting reasonably, in investigating or enforcing its rights under this agreement.

Limitation of Liability
Neither party will be liable for indirect, special, incidental, punitive, or consequential damages arising out of or related to this agreement, however caused, and under whatever cause of action or theory of liability even if a party has been advised of the possibility of such damages.  Adgo.tv’s total aggregate liability shall not exceed (i) for all non-indemnity claims arising out of or related to this agreement: the amount of Adgo.tv’s respective advertising revenue actually received by Adgo.tv (minus the amount of any royalty paid to the Publisher pursuant to the advertising rev share) during the six months prior to the date the liability first arose (“six month limit”), and (ii) for indemnity obligations: two times the six month limit.
Dispute Resolution
The parties shall first attempt to amicably resolve any controversy or dispute of claim between them relating to the TOS with the exception of any intellectual property dispute.  If this fails to settle the matter, parties then agree that the TOS shall be subject to the exclusive jurisdiction and venue in the appropriate court in the United States, and governed, construed, interpreted, and enforced under the laws of the State of Washington, irrespective of its choice of law principals.
Attorney Fees: In the event of any action, mediation, litigation, arbitration, suit, or proceeding arising from or under the terms, provisions, or conditions of the Agreement, the prevailing party shall be entitled to recover reasonable attorney’s fees and costs of litigation or other proceeding.
Severability: If any provision hereof is held invalid or unenforceable by arbitration or a court of competent jurisdiction, such invalidity shall not affect the validity or operation of any other provision and such invalid provision shall be deemed to be severed from the TOS.
Agreement Binding On Successors: 
This Agreement is binding on and will inure to the benefit of the parties and their heirs, administrators, successors, trustees, and assigns.  Notwithstanding, Publisher may not assign this Agreement without the express, written consent of Adgo.tv.  Assignment by Adgo.tv to any entity, which shall acquire all or substantially all of Adgo.tv’s assets, is expressly permitted.
Waiver: No waiver by either party of any default will be deemed as a waiver of any prior or subsequent default of the same or other provisions of the TOS.
Summary
To work with Adgo.tv and to keep your account in good standing, please remember to follow our Terms of Service, and stay up to date if any changes are made. Carefully read the Terms of Service.  Each party represents and warrants that it has all requisite power and authority to execute, deliver, and perform the TOS, and to perform its obligations contemplated hereby.  If you're ever concerned that you might be violating policies, feel free to reach out to us at info@adgo.tv.  Our policy team will be more than happy to answer your questions or concerns.

